"""empty message

Revision ID: 03be64d27f07
Revises: 74125cac593d
Create Date: 2016-03-08 01:36:25.241715

"""

# revision identifiers, used by Alembic.
revision = '03be64d27f07'
down_revision = '74125cac593d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['yelp_category.id'], name=op.f('fk_plan_categories_cat_id_yelp_category')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_categories_plan_id_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_categories'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_categories')
    ### end Alembic commands ###
