"""empty message

Revision ID: 05e085dcc8fa
Revises: 9bbd8e91081e
Create Date: 2016-03-03 15:54:28.327050

"""

# revision identifiers, used by Alembic.
revision = '05e085dcc8fa'
down_revision = '9bbd8e91081e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_itinerary_shares_itinerary_id_itinerary', 'itinerary_shares', type_='foreignkey')
    op.create_foreign_key(op.f('fk_itinerary_shares_itinerary_id_itinerary'), 'itinerary_shares', 'itinerary', ['itinerary_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_itinerary_shares_itinerary_id_itinerary'), 'itinerary_shares', type_='foreignkey')
    op.create_foreign_key('fk_itinerary_shares_itinerary_id_itinerary', 'itinerary_shares', 'itinerary', ['itinerary_id'], ['id'])
    ### end Alembic commands ###
