"""empty message

Revision ID: 1bebb9c46001
Revises: 05e085dcc8fa
Create Date: 2016-03-06 21:51:40.897246

"""

# revision identifiers, used by Alembic.
revision = '1bebb9c46001'
down_revision = '05e085dcc8fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary', sa.Column('starting_address', sa.String(length=2000), nullable=False))
    op.add_column('itinerary', sa.Column('starting_coordinate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_itinerary_starting_coordinate_id_coordinate'), 'itinerary', 'coordinate', ['starting_coordinate_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_itinerary_starting_coordinate_id_coordinate'), 'itinerary', type_='foreignkey')
    op.drop_column('itinerary', 'starting_coordinate_id')
    op.drop_column('itinerary', 'starting_address')
    ### end Alembic commands ###
