"""empty message

Revision ID: 1f1cdbc43652
Revises: 4eb3e6a02464
Create Date: 2016-02-26 14:07:37.935565

"""

# revision identifiers, used by Alembic.
revision = '1f1cdbc43652'
down_revision = '4eb3e6a02464'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('postal_code', sa.String(length=100), nullable=True),
    sa.Column('coordinate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinate.id'], name=op.f('fk_location_coordinate_id_coordinate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.add_column('item', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_item_location_id_location'), 'item', 'location', ['location_id'], ['id'])
    op.add_column('yelp_item', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_yelp_item_yelp_location_id_yelp_location', 'yelp_item', type_='foreignkey')
    op.create_foreign_key(op.f('fk_yelp_item_location_id_location'), 'yelp_item', 'location', ['location_id'], ['id'])
    op.drop_column('yelp_item', 'yelp_location_id')
    op.drop_table('yelp_location')
    op.get_bind().execute(text("SET FOREIGN_KEY_CHECKS=0"))
    op.get_bind().execute(text("DELETE FROM itinerary"))
    op.get_bind().execute(text("DELETE FROM item"))
    op.get_bind().execute(text("DELETE FROM yelp_item"))
    op.get_bind().execute(text("SET FOREIGN_KEY_CHECKS=1"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yelp_location',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('coordinate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinate.id'], name='fk_yelp_location_coordinate_id_coordinate'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.add_column('yelp_item', sa.Column('yelp_location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_yelp_item_location_id_location'), 'yelp_item', type_='foreignkey')
    op.create_foreign_key('fk_yelp_item_yelp_location_id_yelp_location', 'yelp_item', 'yelp_location', ['yelp_location_id'], ['id'])
    op.drop_column('yelp_item', 'location_id')
    op.drop_constraint(op.f('fk_item_location_id_location'), 'item', type_='foreignkey')
    op.drop_column('item', 'location_id')

    op.drop_table('location')
    ### end Alembic commands ###
