"""empty message

Revision ID: 38191dc73a2e
Revises: 03be64d27f07
Create Date: 2016-03-07 21:07:56.216402

"""

# revision identifiers, used by Alembic.
revision = '38191dc73a2e'
down_revision = '03be64d27f07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yelp_category', 'end_time')
    op.drop_column('yelp_category', 'start_time')

    category_table = table("yelp_category",
                           sa.Column('id', sa.Integer(), nullable=False, primary_key=True, unique=True, autoincrement=True),
                           sa.Column('name', sa.String(length=200), nullable=False),
                           sa.Column('search_term', sa.String(length=200), nullable=True),
                           )

    filter_table = table("yelp_search_filter",
                         sa.Column('id', sa.Integer(), nullable=False,  primary_key=True, unique=True, autoincrement=True),
                         sa.Column('filter', sa.String(length=200), nullable=False),
                         sa.Column('category_id', sa.Integer(), nullable=True),
                         )

    op.bulk_insert(category_table,
                   [
                       {
                           "id": 6,
                           "name": "Bowling",
                           "search_term": ""
                       },
                       {
                           "id": 7,
                           "name": "Biking",
                           "search_term": ""
                       },
                       {
                           "id": 8,
                           "name": "Golf",
                           "search_term": ""
                       },
                       {
                           "id": 9,
                           "name": "Parks",
                           "search_term": ""
                       },
                       {
                           "id": 10,
                           "name": "Pools",
                           "search_term": ""
                       },
                       {
                           "id": 11,
                           "name": "Zoos",
                           "search_term": ""
                       },
                       {
                           "id": 12,
                           "name": "Movies",
                           "search_term": ""
                       },{
                           "id": 13,
                           "name": "Jazz Clubs",
                           "search_term": ""
                       },{
                           "id": 14,
                           "name": "Museums",
                           "search_term": ""
                       },{
                           "id": 15,
                           "name": "Bakeries",
                           "search_term": ""
                       },{
                           "id": 16,
                           "name": "Breweries",
                           "search_term": ""
                       },
                       {
                           "id": 17,
                           "name": "Coffee Shops",
                           "search_term": ""
                       },
                       {
                           "id": 18,
                           "name": "Desserts",
                           "search_term": ""
                       },
                       {
                           "id": 19,
                           "name": "Pizza",
                           "search_term": ""
                       },
                       {
                           "id": 20,
                           "name": "Sandwich Shops",
                           "search_term": ""
                       },
                       {
                           "id": 21,
                           "name": "Bars",
                           "search_term": ""
                       },
                       {
                           "id": 22,
                           "name": "Dance Clubs",
                           "search_term": ""
                       },
                       {
                           "id": 23,
                           "name": "Art Galleries",
                           "search_term": ""
                       },
                   ])
    op.bulk_insert(filter_table,
                   [
                       {
                           "id": 15,
                           "filter": "bowling",
                           "category_id": 6
                       },
                       {
                           "id": 16,
                           "filter": "bicyclepaths",
                           "category_id": 7
                       },
                       {
                           "id": 17,
                           "filter": "golf",
                           "category_id": 8
                       },
                       {
                           "id": 18,
                           "filter": "parks",
                           "category_id": 9
                       },
                       {
                           "id": 19,
                           "filter": "playgrounds",
                           "category_id": 9
                       },
                       {
                           "id": 20,
                           "filter": "gardens",
                           "category_id": 9
                       },
                       {
                           "id": 21,
                           "filter": "swimmingpools",
                           "category_id": 10
                       },
                       {
                           "id": 22,
                           "filter": "zoos",
                           "category_id": 11
                       },
                       {
                           "id": 23,
                           "filter": "movietheaters",
                           "category_id": 12
                       },
                       {
                           "id": 24,
                           "filter": "jazzandblues",
                           "category_id": 13
                       },
                       {
                           "id": 25,
                           "filter": "museums",
                           "category_id": 14
                       },
                       {
                           "id": 26,
                           "filter": "bakeries",
                           "category_id": 15
                       },
                       {
                           "id": 27,
                           "filter": "Breweries",
                           "category_id": 16
                       },
                       {
                           "id": 28,
                           "filter": "coffee",
                           "category_id": 17
                       },
                       {
                           "id": 29,
                           "filter": "cafes",
                           "category_id": 17
                       },
                       {
                           "id": 30,
                           "filter": "desserts",
                           "category_id": 18
                       },
                       {
                           "id": 31,
                           "filter": "gelato",
                           "category_id": 18
                       },
                       {
                           "id": 32,
                           "filter": "icecream",
                           "category_id": 18
                       },
                       {
                           "id": 33,
                           "filter": "pizza",
                           "category_id": 19
                       },
                       {
                           "id": 34,
                           "filter": "sandwiches",
                           "category_id": 20
                       },
                       {
                           "id": 35,
                           "filter": "bars",
                           "category_id": 21
                       },
                       {
                           "id": 36,
                           "filter": "danceclubs",
                           "category_id": 22
                       },
                       {
                           "id": 37,
                           "filter": "galleries",
                           "category_id": 23
                       },
                   ])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yelp_category', sa.Column('start_time', mysql.TIME(), nullable=True))
    op.add_column('yelp_category', sa.Column('end_time', mysql.TIME(), nullable=True))
    ### end Alembic commands ###
