"""empty message

Revision ID: 3d173c715442
Revises: 437702866bc1
Create Date: 2016-02-16 20:59:29.464752

"""

# revision identifiers, used by Alembic.
revision = '3d173c715442'
down_revision = '437702866bc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yelp_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('search_term', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yelp_category'))
    )
    op.create_table('yelp_search_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['yelp_category.id'], name=op.f('fk_yelp_search_filter_category_id_yelp_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yelp_search_filter'))
    )
    op.drop_table('search_filter')
    op.drop_table('category')
    op.add_column('item', sa.Column('yelp_category_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_item_category_id_category', 'item', type_='foreignkey')
    op.create_foreign_key(op.f('fk_item_yelp_category_id_yelp_category'), 'item', 'yelp_category', ['yelp_category_id'], ['id'])
    op.drop_column('item', 'category_id')

    op.bulk_insert("yelp_category",
                   [
                       {
                           "id": 1,
                           "name": "breakfast",
                           "search_filter": "breakfast"
                       },
                       {
                           "id": 2,
                           "name": "lunch",
                           "search_filter": "lunch"
                       },
                       {
                           "id": 3,
                           "name": "attraction",
                           "search_filter": "fun"
                       },
                       {
                           "id": 1,
                           "name": "dinner",
                           "search_filter": "dinner"
                       },
                       {
                           "id": 1,
                           "name": "nightlife",
                           "search_filter": ""
                       }

                   ])
    op.bulk_insert("yelp_search_filter",
                   [
                       {
                           "id": 1,
                           "filter": "breakfast_brunch",
                           "category_id": 1
                       },
                       {
                           "id": 2,
                           "filter": "restaurants",
                           "category_id": 2
                       },
                       {
                           "id": 3,
                           "filter": "restaurants",
                           "category_id": 4
                       },
                       {
                           "id": 4,
                           "filter": "localflavor",
                           "category_id": 3
                       },
                       {
                           "id": 5,
                           "filter": "tours",
                           "category_id": 3
                       },
                       {
                           "id": 6,
                           "filter": "parks",
                           "category_id": 3
                       },
                       {
                           "id": 7,
                           "filter": "shopping",
                           "category_id": 3
                       },
                       {
                           "id": 8,
                           "filter": "bars",
                           "category_id": 5
                       },
                       {
                           "id": 9,
                           "filter": "beergardens",
                           "category_id": 5
                       },
                       {
                           "id": 10,
                           "filter": "comedyclubs",
                           "category_id": 5
                       },
                       {
                           "id": 11,
                           "filter": "jazzandblues",
                           "category_id": 5
                       },
                       {
                           "id": 12,
                           "filter": "karaoke",
                           "category_id": 5
                       },
                       {
                           "id": 13,
                           "filter": "poolhalls",
                           "category_id": 5
                       },
                       {
                           "id": 14,
                           "filter": "coffee",
                           "category_id": 5
                       }
                   ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_item_yelp_category_id_yelp_category'), 'item', type_='foreignkey')
    op.create_foreign_key('fk_item_category_id_category', 'item', 'category', ['category_id'], ['id'])
    op.drop_column('item', 'yelp_category_id')
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('search_term', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_filter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filter', sa.VARCHAR(length=200), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_search_filter_category_id_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('yelp_search_filter')
    op.drop_table('yelp_category')
    ### end Alembic commands ###
