"""empty message

Revision ID: 3dadcf1a1cc5
Revises: 11e8f531332d
Create Date: 2016-02-02 22:44:33.108446

"""

# revision identifiers, used by Alembic.
revision = '3dadcf1a1cc5'
down_revision = '11e8f531332d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_authorization',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=300), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_authorization_user_id_user')),
                    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_authorization'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('facebook_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=200), nullable=False))
        batch_op.drop_column('name')

        ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('facebook_id')
        batch_op.drop_column('email')

    op.drop_table('user_authorization')
    ### end Alembic commands ###
