"""empty message

Revision ID: 4eb3e6a02464
Revises: e21746c06769
Create Date: 2016-02-23 02:07:55.191558

"""

# revision identifiers, used by Alembic.
revision = '4eb3e6a02464'
down_revision = 'e21746c06769'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('zip', 'state', 'city', name=op.f('pk_city')))

    with open('./migrations/cities.sql') as sql_file:
        op.get_bind().execute(text(sql_file.read()))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    ### end Alembic commands ###
