"""empty message

Revision ID: 5969f95106fd
Revises: 7744d3ba914a
Create Date: 2016-03-13 03:03:49.912562

"""

# revision identifiers, used by Alembic.
revision = '5969f95106fd'
down_revision = '7744d3ba914a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yelp_item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('yelp_item_id', sa.String(300), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['yelp_category.id'], name=op.f('fk_yelp_item_categories_cat_id_yelp_category')),
    sa.ForeignKeyConstraint(['yelp_item_id'], ['yelp_item.id'], name=op.f('fk_yelp_item_categories_yelp_item_id_yelp_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yelp_item_categories'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yelp_item_categories')
    ### end Alembic commands ###

