"""empty message

Revision ID: 74125cac593d
Revises: f07d4f5de5a1
Create Date: 2016-03-07 23:39:45.958533

"""

# revision identifiers, used by Alembic.
revision = '74125cac593d'
down_revision = 'f07d4f5de5a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('starting_address', sa.String(length=2000), nullable=False),
    sa.Column('starting_coordinate_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starting_coordinate_id'], ['coordinate.id'], name=op.f('fk_plan_starting_coordinate_id_coordinate'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_plan_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan'))
    )
    op.create_table('plan_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Enum('READ', 'EDIT'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_shares_plan_id_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_plan_shares_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_shares'))
    )
    op.add_column('item', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_item_itinerary_id', 'item', type_='foreignkey')
    op.create_foreign_key('fk_item_plan_id', 'item', 'plan', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'itinerary_id')
    op.add_column('rating', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_rating_itinerary_id_itinerary', 'rating', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rating_plan_id_plan'), 'rating', 'plan', ['plan_id'], ['id'])
    op.drop_column('rating', 'itinerary_id')
    op.drop_table('itinerary_shares')
    op.drop_table('itinerary')
    op.drop_table('city')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('itinerary_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_rating_plan_id_plan'), 'rating', type_='foreignkey')
    op.create_foreign_key('fk_rating_itinerary_id_itinerary', 'rating', 'itinerary', ['itinerary_id'], ['id'])
    op.drop_column('rating', 'plan_id')
    op.add_column('item', sa.Column('itinerary_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint('fk_item_plan_id', 'item', type_='foreignkey')
    op.create_foreign_key('fk_item_itinerary_id', 'item', 'itinerary', ['itinerary_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'plan_id')
    op.create_table('itinerary_shares',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('itinerary_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permissions', mysql.ENUM('READ', 'EDIT'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], name='fk_itinerary_shares_itinerary_id_itinerary', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_itinerary_shares_user_id_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('city',
    sa.Column('zip', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('lng', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('zip', 'state', 'city'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('itinerary',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('starting_address', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('starting_coordinate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['starting_coordinate_id'], ['coordinate.id'], name='fk_itinerary_starting_coordinate_id_coordinate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_itinerary_user_id_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('plan_shares')
    op.drop_table('plan')
    ### end Alembic commands ###
