"""empty message

Revision ID: 7744d3ba914a
Revises: f4c858ad7d0c
Create Date: 2016-03-11 23:35:32.091488

"""

# revision identifiers, used by Alembic.
revision = '7744d3ba914a'
down_revision = 'f4c858ad7d0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('plan', sa.Column('description', sa.String(length=10000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'description')
    op.drop_column('item', 'description')
    ### end Alembic commands ###
