"""empty message

Revision ID: 78ca349baf5e
Revises: None
Create Date: 2016-02-04 21:38:51.920431

"""

# revision identifiers, used by Alembic.
revision = '78ca349baf5e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('search_term', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_itinerary_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary'))
    )
    op.create_table('search_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_search_filter_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_filter'))
    )
    op.create_table('user_authorization',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_authorization_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_authorization'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_item_category_id_category')),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], name='fk_item_itinerary_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user_authorization')
    op.drop_table('search_filter')
    op.drop_table('itinerary')
    op.drop_table('user')
    op.drop_table('category')
    ### end Alembic commands ###
