"""empty message

Revision ID: 8778dbfc1fcc
Revises: 3d173c715442
Create Date: 2016-02-20 04:04:26.141435

"""

# revision identifiers, used by Alembic.
revision = '8778dbfc1fcc'
down_revision = '3d173c715442'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coordinate'))
    )
    op.create_table('yelp_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=100), nullable=False),
    sa.Column('coordinate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinate_id'], ['coordinate.id'], name=op.f('fk_yelp_location_coordinate_id_coordinate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yelp_location'))
    )
    op.add_column('item', sa.Column('type', sa.Enum('YELP', 'USER'), nullable=False))
    op.drop_column('itinerary', 'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('item', 'type')
    op.drop_table('yelp_location')
    op.drop_table('coordinate')
    ### end Alembic commands ###
