"""empty message

Revision ID: 8f6bba70ee06
Revises: 78ca349baf5e
Create Date: 2016-02-09 16:16:21.897544

"""

# revision identifiers, used by Alembic.
revision = '8f6bba70ee06'
down_revision = '78ca349baf5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItineraryShares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Enum('READ', 'EDIT'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], name=op.f('fk_ItineraryShares_itinerary_id_itinerary')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ItineraryShares_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ItineraryShares'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItineraryShares')
    ### end Alembic commands ###
