"""empty message

Revision ID: b010848fd8bd
Revises: None
Create Date: 2016-02-02 16:18:29.647754

"""

# revision identifiers, used by Alembic.
revision = 'b010848fd8bd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('search_term', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('User',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Itinerary',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.Column('end_time', sa.DateTime(), nullable=False),
                    sa.Column('city', sa.String(length=200), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('SearchFilter',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('filter', sa.String(length=200), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('itinerary_id', sa.Integer(), nullable=True),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.Column('end_time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
                    sa.ForeignKeyConstraint(['itinerary_id'], ['Itinerary.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Item')
    op.drop_table('SearchFilter')
    op.drop_table('Itinerary')
    op.drop_table('User')
    op.drop_table('Category')
    ### end Alembic commands ###
