"""empty message

Revision ID: e21746c06769
Revises: fee55d4d81d8
Create Date: 2016-02-22 23:50:08.092711

"""

# revision identifiers, used by Alembic.
revision = 'e21746c06769'
down_revision = 'fee55d4d81d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yelp_location', 'postal_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yelp_location', 'postal_code',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    ### end Alembic commands ###
