"""empty message

Revision ID: efe85ec47f7b
Revises: 7744d3ba914a
Create Date: 2016-03-13 11:45:29.020016

"""

# revision identifiers, used by Alembic.
revision = 'efe85ec47f7b'
down_revision = '7744d3ba914a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('city', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'city')
    ### end Alembic commands ###
