"""empty message

Revision ID: f4c858ad7d0c
Revises: 38191dc73a2e
Create Date: 2016-03-07 21:25:35.856050

"""

# revision identifiers, used by Alembic.
revision = 'f4c858ad7d0c'
down_revision = '38191dc73a2e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yelp_category', sa.Column('icon_string', sa.String(length=500), nullable=True))

    command = text("""
        UPDATE yelp_category
        SET icon_string = "food-variant", name="Breakfast"
        WHERE name = "breakfast"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = "food", name="Lunch"
        WHERE name = "lunch"
    """)
    op.get_bind().execute(command)
    command = text("""
        UPDATE yelp_category
        SET icon_string = "food-fork-drink", name="Dinner"
        WHERE name = "dinner"
    """)
    op.get_bind().execute(command)
    command = text("""
        UPDATE yelp_category
        SET icon_string = "airballoon", name="Fun"
        WHERE name = "attraction"
    """)
    op.get_bind().execute(command)
    command = text("""
        UPDATE yelp_category
        SET icon_string = "glass-flute", name="Nightlife"
        WHERE name = "nightlife"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = ""
        WHERE name="Bowling"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = "bike"
        WHERE name="Biking"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = ""
        WHERE name="Golf"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = "pine-tree"
        WHERE name="Parks"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = "swim"
        WHERE name="Pools"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = "cat"
        WHERE name="Zoos"
    """)
    op.get_bind().execute(command)

    command = text("""
        UPDATE yelp_category
        SET icon_string = "theater"
        WHERE name="Movies"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = "saxophone"
        WHERE name="Jazz Clubs"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = ""
        WHERE name="Museums"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = ""
        WHERE name="Bakeries"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = "coffee"
        WHERE name="Coffee Shops"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = "cake-variant"
        WHERE name="Desserts"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = "pizza"
        WHERE name="Pizza"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = ""
        WHERE name="Sandwich Shops"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = "martini"
        WHERE name="Bars"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = ""
        WHERE name="Dance Clubs"
    """)
    op.get_bind().execute(command)

    command=text("""
        UPDATE yelp_category
        SET icon_string = "image-filter-frames"
        WHERE name="Art Galleries"
    """)
    op.get_bind().execute(command)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yelp_category', 'icon_string')
    ### end Alembic commands ###
