"""empty message

Revision ID: f9f293d4688a
Revises: 1f1cdbc43652
Create Date: 2016-03-01 13:52:59.779244

"""

# revision identifiers, used by Alembic.
revision = 'f9f293d4688a'
down_revision = '1f1cdbc43652'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_item_itinerary_id', 'item', type_='foreignkey')
    op.create_foreign_key('fk_item_itinerary_id', 'item', 'itinerary', ['itinerary_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_item_itinerary_id', 'item', type_='foreignkey')
    op.create_foreign_key('fk_item_itinerary_id', 'item', 'itinerary', ['itinerary_id'], ['id'])
    ### end Alembic commands ###
