"""empty message

Revision ID: fa2757e1a81d
Revises: 8f6bba70ee06
Create Date: 2016-02-09 16:20:54.198801

"""

# revision identifiers, used by Alembic.
revision = 'fa2757e1a81d'
down_revision = '8f6bba70ee06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Enum('READ', 'EDIT'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], name=op.f('fk_itinerary_shares_itinerary_id_itinerary')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_itinerary_shares_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_shares'))
    )
    op.drop_table('ItineraryShares')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItineraryShares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('itinerary_id', sa.INTEGER(), nullable=True),
    sa.Column('permissions', sa.VARCHAR(length=4), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('itinerary_shares')
    ### end Alembic commands ###
