"""empty message

Revision ID: fee55d4d81d8
Revises: a3e5b3f14da1
Create Date: 2016-02-20 16:46:30.431146

"""

# revision identifiers, used by Alembic.
revision = 'fee55d4d81d8'
down_revision = 'a3e5b3f14da1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###


    op.drop_constraint('fk_item_yelp_item_id_yelp_item', 'item', type_='foreignkey')

    command = text("""
    ALTER TABLE yelp_item MODIFY id VARCHAR(300)
    """)
    op.get_bind().execute(command)

    command = text("""
    ALTER TABLE item MODIFY yelp_item_id VARCHAR(300)
    """)
    op.get_bind().execute(command)

    op.create_foreign_key('fk_item_yelp_item_id_yelp_item', 'item', 'yelp_item', ['yelp_item_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    pass
